name: build-android.yml

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev \
          python3-pip
        pip install buildozer cython
        pip install --upgrade pip
    
    - name: Build with Buildozer
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: artozymario-apk
        path: bin/*.apk
    
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: artozymario-aab
        path: bin/*.aab
